export const greetings = [
  "Hello! I'm your virtual shopping assistant, here to help you find exactly what you need.",
  "Hi there! I'm your shopping assistant. Let me know what you're looking for and I’ll guide you.",
  "Welcome! I'm here to make your shopping experience smooth and smart. What are you looking for today?",
  "Hey! I'm your personal shopping assistant. Ready to explore some great products together?",
  "Hi! Whether it's tech, fashion, or daily needs, I'm here to assist your shopping journey.",
  "Good to see you! I'm your assistant for all things shopping. How can I help today?",
  "Greetings! I'm an intelligent shopping assistant designed to help you find the best products.",
  "Hello shopper! With me as your assistant, browsing and buying gets easier. What would you like to find?",
  "Hi! I'm your AI shopping companion. Ask me for products, deals, or anything you need.",
  "Welcome Shopper! I'm your friendly shopping assistant—ready to recommend, search, and guide.",
  "Hey there! I’m your virtual assistant for shopping. Let’s get started on finding something great.",
  "Hi again! Need help comparing items or finding top-rated products? I’ve got you covered.",
  "Hello! I'm here to help you shop smarter, faster, and easier. What are you in the mood for?",
  "Hi! I'm your assistant for smart shopping. Let me know your needs, and I’ll handle the rest.",
  "Hello! Your AI shopping helper is ready. What products or categories are you interested in?",
  "Welcome! I'm your digital shopping assistant. Let’s discover exactly what you're looking for.",
  "Hi! I'm here to simplify your shopping experience. Need suggestions or product details?",
  "Hello there! I'm your assistant—trained to help you find products, deals, and more.",
  "Hi! I'm your intelligent shopping partner. Just tell me what you need help with.",
  "Greetings! From product discovery to comparisons, I’m here to help with all your shopping needs.",
  "Hello! I’m your shopping assistant, ready to assist you in finding the perfect products.",
  "Hi! I’m here to make your shopping experience enjoyable and efficient. What can I help you with?",
  "Hello! I’m your personal shopping assistant, designed to help you find the best products quickly and easily.",
  "Hi! I’m your AI shopping assistant, ready to assist you in finding the perfect items for your needs.",
  "Hello! I’m here to help you navigate the world of shopping with ease. What can I assist you with today?",
];

export const clarifications = [
  "Could you please clarify your request?",
  "I'm not sure I understand. Can you rephrase that?",
  "Could you provide more details about what you're looking for?",
  "I didn't quite catch that. Can you explain what you need?",
  "Can you please clarify what you're asking?",
  "I'm a bit confused. Could you elaborate on your request?",
  "Could you please give me more context about your question?",
  "I'm not clear on what you need. Can you clarify?",
  "Can you please specify what you're looking for?",
  "I need a bit more information to assist you. Could you clarify your request?",
  "Could you please provide more details about your question?",
  "I'm not sure I understand your request. Can you clarify?",
  "Can you please explain what you mean?",
  "I didn't quite understand. Could you clarify your question?",
  "Could you please give me more information about what you're asking?",
  "I'm a bit unclear on your request. Can you provide more details?",
  "Can you please clarify what you're looking for?",
  "I'm not sure I follow. Could you explain your request in more detail?",
  "Could you please clarify your question so I can assist you better?",
  "I need a bit more context to help you. Can you clarify your request?",
  "I'm not entirely sure what you mean. Could you please clarify?",
];
